FROM ubuntu:latest

RUN apt-get update && apt-get install -y nginx
RUN rm /etc/nginx/sites-available/default
COPY web.conf /etc/nginx/sites-available/default

EXPOSE 80 81 82

CMD ["nginx", "-g", "daemon off;"] 
